export const categoryDetails = {
  food: {
    key: "food",
    label: "Food & Drinks",
    emoji: "🍕",
    description: "Comfort foods, snacks, and sweet cravings.",
    accent: "from-orange-400 to-rose-400",
    preview: "Pizza",
  },
  animals: {
    key: "animals",
    label: "Animals",
    emoji: "🐾",
    description: "Wild picks, house pets, and zoo favorites.",
    accent: "from-sky-400 via-cyan-400 to-blue-500",
    preview: "Lion",
  },
  movies: {
    key: "movies",
    label: "Movies & TV",
    emoji: "🎬",
    description: "Big screen classics and binge-worthy picks.",
    accent: "from-violet-500 to-fuchsia-500",
    preview: "Titanic",
  },
  places: {
    key: "places",
    label: "Places",
    emoji: "🌍",
    description: "Everyday locations people can picture right away.",
    accent: "from-sky-400 to-emerald-400",
    preview: "Beach",
  },
  jobs: {
    key: "jobs",
    label: "Jobs",
    emoji: "💼",
    description: "Popular professions with easy party-game clues.",
    accent: "from-fuchsia-400 via-pink-500 to-violet-500",
    preview: "Doctor",
  },
  objects: {
    key: "objects",
    label: "Objects",
    emoji: "📱",
    description: "Common things you see, hold, or use every day.",
    accent: "from-indigo-500 to-sky-400",
    preview: "Phone",
  },
  sports: {
    key: "sports",
    label: "Sports",
    emoji: "🏀",
    description: "Fast, familiar, and great for energetic clues.",
    accent: "from-emerald-300 via-teal-300 to-lime-300",
    preview: "Football",
  },
  hobbies: {
    key: "hobbies",
    label: "Hobbies & Activities",
    emoji: "🎨",
    description: "Fun things people do for joy, skill, or chaos.",
    accent: "from-lime-400 to-amber-300",
    preview: "Painting",
  },
};
