export const categorizedWordPairs = {
  food: [
    { wordA: "Pizza", wordB: "Burger" },
    { wordA: "Pasta", wordB: "Noodles" },
    { wordA: "Tea", wordB: "Coffee" },
    { wordA: "Cake", wordB: "Cupcake" },
    { wordA: "Cookie", wordB: "Brownie" },
    { wordA: "Waffle", wordB: "Pancake" },
    { wordA: "Fries", wordB: "Chips" },
    { wordA: "Taco", wordB: "Burrito" },
    { wordA: "Soup", wordB: "Stew" },
    { wordA: "Juice", wordB: "Soda" },
    { wordA: "Lemonade", wordB: "Iced Tea" },
    { wordA: "Sandwich", wordB: "Wrap" },
    { wordA: "Donut", wordB: "Muffin" },
    { wordA: "Croissant", wordB: "Bagel" },
    { wordA: "Milkshake", wordB: "Smoothie" },
    { wordA: "Salad", wordB: "Slaw" },
    { wordA: "Curry", wordB: "Biryani" },
    { wordA: "Omelet", wordB: "Scrambled Eggs" },
    { wordA: "Sausage", wordB: "Hotdog" },
    { wordA: "Ketchup", wordB: "Mayo" },
    { wordA: "Butter", wordB: "Cheese" },
    { wordA: "Apple", wordB: "Orange" },
    { wordA: "Mango", wordB: "Pineapple" },
    { wordA: "Peach", wordB: "Plum" },
    { wordA: "Grapes", wordB: "Blueberries" },
    { wordA: "Strawberry", wordB: "Cherry" },
    { wordA: "Coconut", wordB: "Avocado" },
    { wordA: "Popcorn", wordB: "Nachos" },
    { wordA: "Rice", wordB: "Pulao" },
    { wordA: "Naan", wordB: "Paratha" },
    { wordA: "Pickle", wordB: "Jam" },
    { wordA: "Honey", wordB: "Syrup" },
    { wordA: "Pudding", wordB: "Jelly" },
    { wordA: "Sushi", wordB: "Dumpling" },
    { wordA: "Lasagna", wordB: "Baked Pasta" },
    { wordA: "Espresso", wordB: "Cappuccino" },
  ],
  animals: [
    { wordA: "Lion", wordB: "Tiger" },
    { wordA: "Dog", wordB: "Wolf" },
    { wordA: "Goat", wordB: "Sheep" },
    { wordA: "Crocodile", wordB: "Alligator" },
    { wordA: "Dolphin", wordB: "Whale" },
    { wordA: "Eagle", wordB: "Hawk" },
    { wordA: "Frog", wordB: "Toad" },
    { wordA: "Rabbit", wordB: "Hare" },
    { wordA: "Monkey", wordB: "Ape" },
    { wordA: "Horse", wordB: "Donkey" },
    { wordA: "Leopard", wordB: "Cheetah" },
    { wordA: "Panda", wordB: "Koala" },
    { wordA: "Peacock", wordB: "Parrot" },
    { wordA: "Duck", wordB: "Goose" },
    { wordA: "Crow", wordB: "Raven" },
    { wordA: "Fox", wordB: "Coyote" },
    { wordA: "Mouse", wordB: "Rat" },
    { wordA: "Chicken", wordB: "Turkey" },
    { wordA: "Sparrow", wordB: "Pigeon" },
    { wordA: "Owl", wordB: "Falcon" },
    { wordA: "Penguin", wordB: "Duck" },
    { wordA: "Seal", wordB: "Otter" },
    { wordA: "Buffalo", wordB: "Bison" },
    { wordA: "Crab", wordB: "Lobster" },
    { wordA: "Bee", wordB: "Wasp" },
    { wordA: "Butterfly", wordB: "Moth" },
    { wordA: "Elephant", wordB: "Rhino" },
    { wordA: "Hippo", wordB: "Elephant" },
    { wordA: "Camel", wordB: "Llama" },
    { wordA: "Deer", wordB: "Antelope" },
    { wordA: "Pig", wordB: "Boar" },
    { wordA: "Shark", wordB: "Ray" },
    { wordA: "Swan", wordB: "Goose" },
    { wordA: "Jaguar", wordB: "Leopard" },
    { wordA: "Salmon", wordB: "Tuna" },
    { wordA: "Turtle", wordB: "Tortoise" },
  ],
  sports: [
    { wordA: "Football", wordB: "Rugby" },
    { wordA: "Tennis", wordB: "Badminton" },
    { wordA: "Baseball", wordB: "Softball" },
    { wordA: "Pool", wordB: "Snooker" },
    { wordA: "Running", wordB: "Marathon" },
    { wordA: "Skating", wordB: "Skateboarding" },
    { wordA: "Formula One", wordB: "MotoGP" },
    { wordA: "Judo", wordB: "Karate" },
    { wordA: "Basketball", wordB: "Netball" },
    { wordA: "Volleyball", wordB: "Handball" },
    { wordA: "Boxing", wordB: "Wrestling" },
    { wordA: "Rowing", wordB: "Canoeing" },
    { wordA: "Surfing", wordB: "Swimming" },
    { wordA: "Skiing", wordB: "Snowboarding" },
    { wordA: "Fencing", wordB: "Archery" },
    { wordA: "Cycling", wordB: "BMX" },
    { wordA: "Hockey", wordB: "Lacrosse" },
    { wordA: "Cricket", wordB: "Baseball" },
    { wordA: "Bowling", wordB: "Darts" },
    { wordA: "Gymnastics", wordB: "Diving" },
    { wordA: "Chess", wordB: "Checkers" },
    { wordA: "Kayaking", wordB: "Rafting" },
    { wordA: "Snorkeling", wordB: "Scuba" },
    { wordA: "Sprint", wordB: "Jogging" },
    { wordA: "Weightlifting", wordB: "Bodybuilding" },
    { wordA: "Yoga", wordB: "Pilates" },
    { wordA: "Climbing", wordB: "Hiking" },
    { wordA: "Polo", wordB: "Horse Riding" },
    { wordA: "Sailing", wordB: "Boating" },
    { wordA: "Billiards", wordB: "Carrom" },
    { wordA: "Dodgeball", wordB: "Kickball" },
    { wordA: "Aerobics", wordB: "Zumba" },
    { wordA: "Triathlon", wordB: "Marathon" },
    { wordA: "Water Polo", wordB: "Polo" },
    { wordA: "Golf", wordB: "Croquet" },
    { wordA: "Ice Hockey", wordB: "Field Hockey" },
  ],
  jobs: [
    { wordA: "Doctor", wordB: "Nurse" },
    { wordA: "Teacher", wordB: "Professor" },
    { wordA: "Chef", wordB: "Baker" },
    { wordA: "Actor", wordB: "Director" },
    { wordA: "Designer", wordB: "Architect" },
    { wordA: "Writer", wordB: "Journalist" },
    { wordA: "Police", wordB: "Soldier" },
    { wordA: "Singer", wordB: "Dancer" },
    { wordA: "Pilot", wordB: "Driver" },
    { wordA: "Barber", wordB: "Stylist" },
    { wordA: "Electrician", wordB: "Mechanic" },
    { wordA: "Farmer", wordB: "Gardener" },
    { wordA: "Dentist", wordB: "Surgeon" },
    { wordA: "Waiter", wordB: "Cashier" },
    { wordA: "Judge", wordB: "Lawyer" },
    { wordA: "Scientist", wordB: "Researcher" },
    { wordA: "Plumber", wordB: "Technician" },
    { wordA: "Photographer", wordB: "Cameraman" },
    { wordA: "Firefighter", wordB: "Rescuer" },
    { wordA: "Therapist", wordB: "Counselor" },
    { wordA: "Developer", wordB: "Engineer" },
    { wordA: "Tailor", wordB: "Fashion Designer" },
    { wordA: "Coach", wordB: "Trainer" },
    { wordA: "Builder", wordB: "Carpenter" },
    { wordA: "Librarian", wordB: "Teacher" },
    { wordA: "Painter", wordB: "Artist" },
    { wordA: "DJ", wordB: "Musician" },
    { wordA: "Vet", wordB: "Doctor" },
    { wordA: "Receptionist", wordB: "Secretary" },
    { wordA: "Banker", wordB: "Accountant" },
    { wordA: "Reporter", wordB: "Anchor" },
    { wordA: "Guard", wordB: "Police" },
    { wordA: "Florist", wordB: "Gardener" },
    { wordA: "Detective", wordB: "Inspector" },
    { wordA: "Manager", wordB: "Supervisor" },
    { wordA: "Pharmacist", wordB: "Chemist" },
  ],
  objects: [
    { wordA: "Phone", wordB: "Laptop" },
    { wordA: "Chair", wordB: "Sofa" },
    { wordA: "Pen", wordB: "Pencil" },
    { wordA: "Bottle", wordB: "Glass" },
    { wordA: "Fork", wordB: "Spoon" },
    { wordA: "Lamp", wordB: "Candle" },
    { wordA: "Backpack", wordB: "Bag" },
    { wordA: "Speaker", wordB: "Headphones" },
    { wordA: "Table", wordB: "Desk" },
    { wordA: "Keyboard", wordB: "Mouse" },
    { wordA: "Plate", wordB: "Bowl" },
    { wordA: "Cup", wordB: "Mug" },
    { wordA: "Blanket", wordB: "Pillow" },
    { wordA: "Mirror", wordB: "Window" },
    { wordA: "Clock", wordB: "Watch" },
    { wordA: "Fan", wordB: "Cooler" },
    { wordA: "Remote", wordB: "Controller" },
    { wordA: "Camera", wordB: "Binoculars" },
    { wordA: "Scissors", wordB: "Knife" },
    { wordA: "Toothbrush", wordB: "Comb" },
    { wordA: "Wallet", wordB: "Purse" },
    { wordA: "Helmet", wordB: "Cap" },
    { wordA: "Basket", wordB: "Box" },
    { wordA: "Book", wordB: "Magazine" },
    { wordA: "TV", wordB: "Projector" },
    { wordA: "Charger", wordB: "Adapter" },
    { wordA: "Soap", wordB: "Shampoo" },
    { wordA: "Towel", wordB: "Napkin" },
    { wordA: "Umbrella", wordB: "Raincoat" },
    { wordA: "Fridge", wordB: "Microwave" },
    { wordA: "Oven", wordB: "Toaster" },
    { wordA: "Lock", wordB: "Key" },
    { wordA: "Ring", wordB: "Bracelet" },
    { wordA: "Toy", wordB: "Doll" },
    { wordA: "Jar", wordB: "Bottle" },
    { wordA: "Notebook", wordB: "Diary" },
  ],
  places: [
    { wordA: "Beach", wordB: "Island" },
    { wordA: "School", wordB: "University" },
    { wordA: "Cafe", wordB: "Restaurant" },
    { wordA: "Library", wordB: "Museum" },
    { wordA: "Airport", wordB: "Station" },
    { wordA: "Market", wordB: "Mall" },
    { wordA: "Farm", wordB: "Village" },
    { wordA: "Cinema", wordB: "Theater" },
    { wordA: "Park", wordB: "Garden" },
    { wordA: "Hospital", wordB: "Clinic" },
    { wordA: "Hotel", wordB: "Hostel" },
    { wordA: "Temple", wordB: "Church" },
    { wordA: "Stadium", wordB: "Arena" },
    { wordA: "Office", wordB: "Factory" },
    { wordA: "Bridge", wordB: "Tunnel" },
    { wordA: "Castle", wordB: "Palace" },
    { wordA: "Bank", wordB: "Post Office" },
    { wordA: "Zoo", wordB: "Aquarium" },
    { wordA: "Harbor", wordB: "Port" },
    { wordA: "Mountain", wordB: "Hill" },
    { wordA: "River", wordB: "Lake" },
    { wordA: "Playground", wordB: "Park" },
    { wordA: "Apartment", wordB: "House" },
    { wordA: "Shop", wordB: "Market" },
    { wordA: "Museum", wordB: "Gallery" },
    { wordA: "School", wordB: "Classroom" },
    { wordA: "Kitchen", wordB: "Dining Room" },
    { wordA: "Bathroom", wordB: "Bedroom" },
    { wordA: "Garage", wordB: "Basement" },
    { wordA: "Balcony", wordB: "Terrace" },
    { wordA: "Bakery", wordB: "Cafe" },
    { wordA: "Station", wordB: "Terminal" },
    { wordA: "Temple", wordB: "Mosque" },
    { wordA: "College", wordB: "School" },
    { wordA: "Village", wordB: "Town" },
    { wordA: "Forest", wordB: "Park" },
  ],
  movies: [
    { wordA: "Batman", wordB: "Superman" },
    { wordA: "Joker", wordB: "Harley Quinn" },
    { wordA: "Iron Man", wordB: "Captain America" },
    { wordA: "Hulk", wordB: "Thor" },
    { wordA: "Spider-Man", wordB: "Ant-Man" },
    { wordA: "Frozen", wordB: "Moana" },
    { wordA: "Toy Story", wordB: "Cars" },
    { wordA: "Avengers", wordB: "Justice League" },
    { wordA: "Harry Potter", wordB: "Lord of the Rings" },
    { wordA: "Friends", wordB: "How I Met Your Mother" },
    { wordA: "Tom and Jerry", wordB: "Looney Tunes" },
    { wordA: "Naruto", wordB: "Dragon Ball" },
    { wordA: "Disney", wordB: "Pixar" },
    { wordA: "Barbie", wordB: "Bratz" },
    { wordA: "Guitar", wordB: "Ukulele" },
    { wordA: "Piano", wordB: "Keyboard" },
    { wordA: "Violin", wordB: "Cello" },
    { wordA: "Trumpet", wordB: "Saxophone" },
    { wordA: "Drums", wordB: "Bongo" },
    { wordA: "Singer", wordB: "Rapper" },
    { wordA: "Concert", wordB: "Festival" },
    { wordA: "Comedy", wordB: "Drama" },
    { wordA: "Thriller", wordB: "Horror" },
    { wordA: "Cartoon", wordB: "Anime" },
    { wordA: "Radio", wordB: "Podcast" },
    { wordA: "Movie", wordB: "Series" },
    { wordA: "Stage", wordB: "Screen" },
    { wordA: "DJ", wordB: "Band" },
    { wordA: "Mario", wordB: "Sonic" },
    { wordA: "Minions", wordB: "Smurfs" },
    { wordA: "Mickey Mouse", wordB: "Donald Duck" },
    { wordA: "Scooby-Doo", wordB: "Tom and Jerry" },
    { wordA: "Netflix", wordB: "YouTube" },
    { wordA: "Magic Show", wordB: "Circus" },
    { wordA: "Documentary", wordB: "Biopic" },
    { wordA: "Sitcom", wordB: "Soap Opera" },
  ],
  technology: [
    { wordA: "Phone", wordB: "Tablet" },
    { wordA: "Laptop", wordB: "Computer" },
    { wordA: "App", wordB: "Website" },
    { wordA: "Keyboard", wordB: "Mouse" },
    { wordA: "Chrome", wordB: "Safari" },
    { wordA: "Android", wordB: "iPhone" },
    { wordA: "Wi-Fi", wordB: "Bluetooth" },
    { wordA: "USB", wordB: "Charger" },
    { wordA: "Camera", wordB: "Webcam" },
    { wordA: "Router", wordB: "Modem" },
    { wordA: "Password", wordB: "PIN" },
    { wordA: "Email", wordB: "Message" },
    { wordA: "Google", wordB: "Bing" },
    { wordA: "Zoom", wordB: "Meet" },
    { wordA: "Instagram", wordB: "Snapchat" },
    { wordA: "YouTube", wordB: "TikTok" },
    { wordA: "Cloud", wordB: "Server" },
    { wordA: "Monitor", wordB: "TV" },
    { wordA: "Printer", wordB: "Scanner" },
    { wordA: "Robot", wordB: "Drone" },
    { wordA: "AI", wordB: "Chatbot" },
    { wordA: "Gamepad", wordB: "Joystick" },
    { wordA: "Earbuds", wordB: "Headphones" },
    { wordA: "Smartwatch", wordB: "Fitness Band" },
    { wordA: "Cable", wordB: "Wire" },
    { wordA: "Battery", wordB: "Power Bank" },
    { wordA: "Hard Drive", wordB: "Pen Drive" },
    { wordA: "Touchpad", wordB: "Mouse" },
    { wordA: "Microphone", wordB: "Webcam" },
    { wordA: "CPU", wordB: "Monitor" },
    { wordA: "Speaker", wordB: "Mic" },
    { wordA: "QR Code", wordB: "Barcode" },
    { wordA: "Software", wordB: "Program" },
    { wordA: "Update", wordB: "Download" },
    { wordA: "Firewall", wordB: "Antivirus" },
    { wordA: "Remote", wordB: "Controller" },
  ],
  vehicles: [
    { wordA: "Car", wordB: "Bike" },
    { wordA: "Bus", wordB: "Van" },
    { wordA: "Train", wordB: "Metro" },
    { wordA: "Plane", wordB: "Helicopter" },
    { wordA: "Scooter", wordB: "Motorcycle" },
    { wordA: "Ship", wordB: "Boat" },
    { wordA: "Truck", wordB: "Trailer" },
    { wordA: "Bicycle", wordB: "Motorbike" },
    { wordA: "Tram", wordB: "Bus" },
    { wordA: "Jeep", wordB: "SUV" },
    { wordA: "Sedan", wordB: "Hatchback" },
    { wordA: "Tractor", wordB: "Bulldozer" },
    { wordA: "Canoe", wordB: "Kayak" },
    { wordA: "Ferry", wordB: "Ship" },
    { wordA: "Rocket", wordB: "Plane" },
    { wordA: "Van", wordB: "Minibus" },
    { wordA: "Pickup", wordB: "Truck" },
    { wordA: "Rickshaw", wordB: "Taxi" },
    { wordA: "Cruise", wordB: "Ferry" },
    { wordA: "Hoverboard", wordB: "Segway" },
    { wordA: "ATV", wordB: "Jeep" },
    { wordA: "Motorboat", wordB: "Jet Ski" },
    { wordA: "Glider", wordB: "Plane" },
    { wordA: "Tank", wordB: "Truck" },
    { wordA: "Wagon", wordB: "Cart" },
    { wordA: "Limousine", wordB: "Sedan" },
    { wordA: "Police Car", wordB: "Ambulance" },
    { wordA: "School Bus", wordB: "Coach" },
    { wordA: "Convertible", wordB: "Coupe" },
    { wordA: "Drone", wordB: "Helicopter" },
    { wordA: "Bicycle", wordB: "Rickshaw" },
    { wordA: "Metro", wordB: "Tram" },
    { wordA: "Sailboat", wordB: "Yacht" },
    { wordA: "Bulldozer", wordB: "Excavator" },
    { wordA: "Ambulance", wordB: "Fire Truck" },
    { wordA: "Submarine", wordB: "Ship" },
  ],
  hobbies: [
    { wordA: "Painting", wordB: "Drawing" },
    { wordA: "Singing", wordB: "Dancing" },
    { wordA: "Reading", wordB: "Writing" },
    { wordA: "Cooking", wordB: "Baking" },
    { wordA: "Hiking", wordB: "Camping" },
    { wordA: "Fishing", wordB: "Boating" },
    { wordA: "Yoga", wordB: "Pilates" },
    { wordA: "Knitting", wordB: "Crochet" },
    { wordA: "Swimming", wordB: "Jogging" },
    { wordA: "Gardening", wordB: "Farming" },
    { wordA: "Photography", wordB: "Filming" },
    { wordA: "Chess", wordB: "Puzzles" },
    { wordA: "Gaming", wordB: "Streaming" },
    { wordA: "Cycling", wordB: "Jogging" },
    { wordA: "Collecting", wordB: "Trading" },
    { wordA: "Pottery", wordB: "Sculpting" },
    { wordA: "Journaling", wordB: "Writing" },
    { wordA: "Scrapbooking", wordB: "Crafting" },
    { wordA: "Meditating", wordB: "Yoga" },
    { wordA: "Blogging", wordB: "Vlogging" },
    { wordA: "Birdwatching", wordB: "Hiking" },
    { wordA: "Origami", wordB: "Crafting" },
    { wordA: "Karaoke", wordB: "Singing" },
    { wordA: "Sewing", wordB: "Knitting" },
    { wordA: "Calligraphy", wordB: "Drawing" },
    { wordA: "Drumming", wordB: "Guitar" },
    { wordA: "Cards", wordB: "Chess" },
    { wordA: "Traveling", wordB: "Camping" },
    { wordA: "Running", wordB: "Cycling" },
    { wordA: "Surfing", wordB: "Swimming" },
    { wordA: "Acting", wordB: "Dancing" },
    { wordA: "Workout", wordB: "Yoga" },
    { wordA: "Painting", wordB: "Coloring" },
    { wordA: "Baking", wordB: "Grilling" },
    { wordA: "Reading", wordB: "Podcasting" },
    { wordA: "Fishing", wordB: "Camping" },
  ],
  nature: [
    { wordA: "River", wordB: "Lake" },
    { wordA: "Mountain", wordB: "Hill" },
    { wordA: "Forest", wordB: "Jungle" },
    { wordA: "Ocean", wordB: "Sea" },
    { wordA: "Rain", wordB: "Snow" },
    { wordA: "Sun", wordB: "Moon" },
    { wordA: "Cloud", wordB: "Fog" },
    { wordA: "Thunder", wordB: "Lightning" },
    { wordA: "Flower", wordB: "Leaf" },
    { wordA: "Sand", wordB: "Dust" },
    { wordA: "Island", wordB: "Beach" },
    { wordA: "Waterfall", wordB: "River" },
    { wordA: "Volcano", wordB: "Mountain" },
    { wordA: "Storm", wordB: "Wind" },
    { wordA: "Tree", wordB: "Bush" },
    { wordA: "Desert", wordB: "Dune" },
    { wordA: "Pond", wordB: "Lake" },
    { wordA: "Glacier", wordB: "Iceberg" },
    { wordA: "Valley", wordB: "Canyon" },
    { wordA: "Meadow", wordB: "Field" },
    { wordA: "Rainbow", wordB: "Sunset" },
    { wordA: "Sunrise", wordB: "Sunset" },
    { wordA: "Soil", wordB: "Mud" },
    { wordA: "Branch", wordB: "Leaf" },
    { wordA: "Wave", wordB: "Tide" },
    { wordA: "Moss", wordB: "Grass" },
    { wordA: "Seed", wordB: "Flower" },
    { wordA: "Coral", wordB: "Seaweed" },
    { wordA: "Pebble", wordB: "Shell" },
    { wordA: "Cliff", wordB: "Hill" },
    { wordA: "Cave", wordB: "Valley" },
    { wordA: "Rainforest", wordB: "Jungle" },
    { wordA: "Stream", wordB: "River" },
    { wordA: "Moon", wordB: "Star" },
    { wordA: "Hurricane", wordB: "Tornado" },
    { wordA: "Coast", wordB: "Beach" },
  ],
  clothing: [
    { wordA: "Shirt", wordB: "T-Shirt" },
    { wordA: "Jeans", wordB: "Trousers" },
    { wordA: "Skirt", wordB: "Dress" },
    { wordA: "Jacket", wordB: "Coat" },
    { wordA: "Hat", wordB: "Cap" },
    { wordA: "Shoes", wordB: "Sandals" },
    { wordA: "Socks", wordB: "Gloves" },
    { wordA: "Sweater", wordB: "Hoodie" },
    { wordA: "Scarf", wordB: "Shawl" },
    { wordA: "Belt", wordB: "Tie" },
    { wordA: "Suit", wordB: "Blazer" },
    { wordA: "Shorts", wordB: "Track Pants" },
    { wordA: "Boots", wordB: "Sneakers" },
    { wordA: "Pajamas", wordB: "Robe" },
    { wordA: "Uniform", wordB: "Jersey" },
    { wordA: "Bracelet", wordB: "Bangle" },
    { wordA: "Blouse", wordB: "Shirt" },
    { wordA: "Kurta", wordB: "Shirt" },
    { wordA: "Saree", wordB: "Lehenga" },
    { wordA: "Kimono", wordB: "Robe" },
    { wordA: "Tie", wordB: "Bow Tie" },
    { wordA: "Tank Top", wordB: "T-Shirt" },
    { wordA: "Raincoat", wordB: "Jacket" },
    { wordA: "Helmet", wordB: "Cap" },
    { wordA: "Beanie", wordB: "Cap" },
    { wordA: "Slippers", wordB: "Sandals" },
    { wordA: "Loafers", wordB: "Sneakers" },
    { wordA: "Sunglasses", wordB: "Glasses" },
    { wordA: "Vest", wordB: "Jacket" },
    { wordA: "Tunic", wordB: "Dress" },
    { wordA: "Apron", wordB: "Uniform" },
    { wordA: "Cardigan", wordB: "Sweater" },
    { wordA: "Necklace", wordB: "Scarf" },
    { wordA: "Earrings", wordB: "Bracelet" },
    { wordA: "Watch", wordB: "Bracelet" },
    { wordA: "Pajamas", wordB: "Tracksuit" },
  ],
  brands: [
    { wordA: "Coca-Cola", wordB: "Pepsi" },
    { wordA: "Nike", wordB: "Adidas" },
    { wordA: "Apple", wordB: "Samsung" },
    { wordA: "McDonald's", wordB: "Burger King" },
    { wordA: "KFC", wordB: "Subway" },
    { wordA: "Netflix", wordB: "Amazon Prime" },
    { wordA: "Instagram", wordB: "Snapchat" },
    { wordA: "Uber", wordB: "Ola" },
    { wordA: "Google", wordB: "Microsoft" },
    { wordA: "BMW", wordB: "Audi" },
    { wordA: "Toyota", wordB: "Honda" },
    { wordA: "Puma", wordB: "Reebok" },
    { wordA: "Zara", wordB: "H&M" },
    { wordA: "Tesla", wordB: "BYD" },
    { wordA: "PlayStation", wordB: "Xbox" },
    { wordA: "Canon", wordB: "Nikon" },
    { wordA: "Dell", wordB: "HP" },
    { wordA: "Asus", wordB: "Acer" },
    { wordA: "Vivo", wordB: "Oppo" },
    { wordA: "Starbucks", wordB: "Dunkin" },
    { wordA: "Domino's", wordB: "Pizza Hut" },
    { wordA: "Amazon", wordB: "Flipkart" },
    { wordA: "LG", wordB: "Sony" },
    { wordA: "Nokia", wordB: "Motorola" },
    { wordA: "WhatsApp", wordB: "Telegram" },
    { wordA: "Airbnb", wordB: "OYO" },
    { wordA: "Rolex", wordB: "Casio" },
    { wordA: "KitKat", wordB: "Snickers" },
    { wordA: "Visa", wordB: "Mastercard" },
    { wordA: "FedEx", wordB: "DHL" },
    { wordA: "Levi's", wordB: "Wrangler" },
    { wordA: "Spotify", wordB: "Apple Music" },
    { wordA: "Reddit", wordB: "Twitter" },
    { wordA: "Hyundai", wordB: "Kia" },
    { wordA: "Shell", wordB: "BP" },
    { wordA: "Google Maps", wordB: "Apple Maps" },
  ],
  countriesCities: [
    { wordA: "India", wordB: "Pakistan" },
    { wordA: "Japan", wordB: "South Korea" },
    { wordA: "Canada", wordB: "USA" },
    { wordA: "Spain", wordB: "Portugal" },
    { wordA: "Australia", wordB: "New Zealand" },
    { wordA: "Germany", wordB: "Switzerland" },
    { wordA: "Norway", wordB: "Sweden" },
    { wordA: "Thailand", wordB: "Indonesia" },
    { wordA: "Paris", wordB: "London" },
    { wordA: "Tokyo", wordB: "Seoul" },
    { wordA: "Delhi", wordB: "Mumbai" },
    { wordA: "Dubai", wordB: "Doha" },
    { wordA: "Rome", wordB: "Athens" },
    { wordA: "Sydney", wordB: "Melbourne" },
    { wordA: "Toronto", wordB: "Vancouver" },
    { wordA: "Beijing", wordB: "Shanghai" },
    { wordA: "Cairo", wordB: "Istanbul" },
    { wordA: "Moscow", wordB: "Warsaw" },
    { wordA: "Lisbon", wordB: "Madrid" },
    { wordA: "Bangkok", wordB: "Singapore" },
    { wordA: "Berlin", wordB: "Vienna" },
    { wordA: "Zurich", wordB: "Geneva" },
    { wordA: "New York", wordB: "Chicago" },
    { wordA: "Los Angeles", wordB: "Miami" },
    { wordA: "San Francisco", wordB: "Seattle" },
    { wordA: "Jaipur", wordB: "Udaipur" },
    { wordA: "Chennai", wordB: "Bangalore" },
    { wordA: "Kolkata", wordB: "Dhaka" },
    { wordA: "Pune", wordB: "Hyderabad" },
    { wordA: "Manchester", wordB: "Liverpool" },
    { wordA: "Kyoto", wordB: "Osaka" },
    { wordA: "Phuket", wordB: "Bali" },
    { wordA: "Venice", wordB: "Florence" },
    { wordA: "Brussels", wordB: "Amsterdam" },
    { wordA: "Prague", wordB: "Budapest" },
    { wordA: "Dublin", wordB: "Edinburgh" },
  ],
};

export const wordPairs = Object.values(categorizedWordPairs).flat();

export function getRandomPair(category) {
  const pool = category ? categorizedWordPairs[category] ?? wordPairs : wordPairs;
  return pool[Math.floor(Math.random() * pool.length)];
}
