const createEasyEntries = (words, hint) => words.map((word) => ({ word, hint }));

export const easyWordAdditions = {
  food: createEasyEntries([
    "Bread",
    "Egg",
    "Milk",
    "Butter",
    "Cheeseburger",
    "Wrap",
    "Toast",
    "Jam",
    "Honey",
    "Corn",
    "Beans",
    "Peas",
    "Potato",
    "Tomato",
    "Onion",
    "Carrot",
    "Cabbage",
    "Spinach",
    "Garlic",
    "Ginger",
    "Chips",
    "Nachos",
    "Ketchup",
    "Mayonnaise",
    "Pickle",
    "Paratha",
    "Roti",
    "Idli",
    "Dosa",
    "Samosa",
    "Pakora",
    "Kebab",
    "Paneer",
    "Fish",
    "Chicken",
    "Mutton",
    "Shrimp",
    "Oats",
    "Cereal",
    "Yogurt",
    "Curd",
    "Ladoo",
    "Halwa",
    "Jalebi",
    "Rasgulla",
    "Pudding",
    "Pie",
    "Pastry",
    "Momo",
    "Spring Roll",
    "Burger Meal",
    "Fried Rice",
    "Manchurian",
    "Macaroni",
    "Spaghetti",
    "Avocado",
    "Papaya",
    "Pineapple",
    "Strawberry",
    "Cherry",
    "Kiwi",
    "Pear",
    "Coconut",
    "Guava",
    "Lemon",
  ], "Tasty"),
  animals: createEasyEntries([
    "Ant",
    "Beetle",
    "Butterfly",
    "Bee",
    "Mosquito",
    "Fly",
    "Crow",
    "Sparrow",
    "Pigeon",
    "Hen",
    "Rooster",
    "Ostrich",
    "Donkey",
    "Mule",
    "Buffalo",
    "Ox",
    "Bull",
    "Calf",
    "Kitten",
    "Puppy",
    "Hamster",
    "Guinea Pig",
    "Mouse",
    "Rat",
    "Squirrel",
    "Bat",
    "Seal",
    "Sea Lion",
    "Jellyfish",
    "Starfish",
    "Crab",
    "Lobster",
    "Seahorse",
    "Snail",
    "Slug",
    "Worm",
    "Spider",
    "Scorpion",
    "Lizard",
    "Gecko",
    "Iguana",
    "Tortoise",
    "Turtle",
    "Swan",
    "Goose",
    "Flamingo",
    "Pelican",
    "Woodpecker",
    "Falcon",
    "Chimpanzee",
    "Gorilla",
    "Orangutan",
    "Hyena",
    "Rhino",
    "Moose",
    "Bison",
    "Mole",
    "Raccoon",
    "Badger",
    "Meerkat",
    "Jaguar",
    "Panther",
    "Cheetah",
    "Turkey",
    "Yak",
  ], "Wild"),
  sports: createEasyEntries([
    "Kabaddi",
    "Kho Kho",
    "Long Jump",
    "High Jump",
    "Shot Put",
    "Discus Throw",
    "Pole Vault",
    "Sprint",
    "Relay Race",
    "Hurdles",
    "Triathlon",
    "Biathlon",
    "Weightlifting",
    "Powerlifting",
    "Bodybuilding",
    "Crossfit",
    "Aerobics",
    "Zumba",
    "Pilates",
    "Taekwondo",
    "Kickboxing",
    "Muay Thai",
    "MMA",
    "Sumo",
    "Ice Hockey",
    "Figure Skating",
    "Ice Skating",
    "Roller Skating",
    "Inline Skating",
    "BMX",
    "Mountain Biking",
    "Road Cycling",
    "Sailing",
    "Canoeing",
    "Kayaking",
    "Rafting",
    "Climbing",
    "Bouldering",
    "Horse Riding",
    "Polo",
    "Squash",
    "Pickleball",
    "Dodgeball",
    "Frisbee",
    "Ultimate Frisbee",
    "Netball",
    "Base Jumping",
    "Parkour",
    "E Sports",
    "Arm Wrestling",
    "Foosball",
    "Darts",
    "Carrom",
    "Chess Boxing",
    "Sepak Takraw",
    "Hand Cycling",
    "Paddle Boarding",
    "Windsurfing",
    "Jet Skiing",
    "Horse Racing",
    "Synchronized Swimming",
    "Beach Volleyball",
    "Beach Soccer",
    "Futsal",
    "Curling",
  ], "Active"),
  jobs: createEasyEntries([
    "Painter",
    "Cleaner",
    "Guard",
    "Watchman",
    "Shopkeeper",
    "Manager",
    "Receptionist",
    "Cook",
    "Delivery Boy",
    "Courier",
    "Butcher",
    "Florist",
    "Gardener",
    "Mason",
    "Welder",
    "Carpenter",
    "Blacksmith",
    "Goldsmith",
    "Jeweler",
    "Banker",
    "Accountant",
    "Auditor",
    "Clerk",
    "Typist",
    "Secretary",
    "Host",
    "RJ",
    "DJ",
    "Musician",
    "Comedian",
    "Magician",
    "Coach",
    "Trainer",
    "Referee",
    "Umpire",
    "Office Manager",
    "Store Manager",
    "Security Guard",
    "Bus Driver",
    "Truck Driver",
    "Conductor",
    "Ticket Checker",
    "Travel Agent",
    "Guide",
    "Translator",
    "Interpreter",
    "Editor",
    "Animator",
    "Illustrator",
    "Programmer",
    "Tester",
    "Data Analyst",
    "Businessman",
    "Entrepreneur",
    "Salesman",
    "Salesperson",
    "Marketing Expert",
    "Makeup Artist",
    "Stylist",
    "Hairdresser",
    "Veterinarian",
    "Pharmacist",
    "Surgeon",
    "Front Desk Clerk",
    "Plasterer",
  ], "Working"),
  objects: createEasyEntries([
    "Pencil",
    "Eraser",
    "Sharpener",
    "Notebook",
    "Ruler",
    "Marker",
    "Crayon",
    "Paintbrush",
    "Bucket",
    "Mug",
    "Cup",
    "Glass",
    "Jug",
    "Bowl",
    "Pan",
    "Pot",
    "Kettle",
    "Stove",
    "Oven",
    "Mixer",
    "Blender",
    "Grinder",
    "Fridge",
    "Freezer",
    "Curtain",
    "Window",
    "Door",
    "Lock",
    "Key",
    "Bell",
    "Mat",
    "Rug",
    "Bed",
    "Mattress",
    "Desk",
    "Drawer",
    "Cupboard",
    "Shelf",
    "Hanger",
    "Basket",
    "Soap",
    "Shampoo",
    "Towel",
    "Brush",
    "Razor",
    "Bucket Hat",
    "Cap",
    "Shoes",
    "Slippers",
    "Socks",
    "Jacket",
    "Shirt",
    "Pants",
    "Belt",
    "Zip",
    "Needle",
    "Thread",
    "Tape",
    "Glue",
    "Stapler",
    "Charger Cable",
    "Calculator",
    "Torch",
    "Bin",
    "Dustpan",
  ], "Useful"),
  places: createEasyEntries([
    "Home",
    "Kitchen",
    "Bedroom",
    "Bathroom",
    "Balcony",
    "Garden",
    "Garage",
    "Terrace",
    "Street",
    "Road",
    "Highway",
    "Crossroad",
    "Bus Stop",
    "Railway Station",
    "Metro Station",
    "Bus Stand",
    "Petrol Pump",
    "Police Station",
    "Fire Station",
    "Court",
    "Post Office",
    "Bookstore",
    "Toy Store",
    "Supermarket",
    "Grocery Store",
    "Fruit Shop",
    "Salon",
    "Spa",
    "Clinic",
    "Pharmacy",
    "College",
    "Classroom",
    "Playground",
    "Hostel",
    "Dorm",
    "Warehouse",
    "Workshop",
    "Studio",
    "Wedding Hall",
    "Banquet Hall",
    "Swimming Pool",
    "Water Park",
    "Resort",
    "Camp",
    "Campground",
    "Airport Lounge",
    "Parking Lot",
    "Lift",
    "Stairs",
    "Roof",
    "Basement",
    "Harbor Port",
    "Pier",
    "Temple Hall",
    "Mosque",
    "Church",
    "Monastery",
    "Cottage",
    "Cabin",
    "Shop",
    "Cyber Cafe",
    "Food Court",
    "Arcade",
    "Gym Hall",
    "Skating Rink",
  ], "Popular"),
  movies: createEasyEntries([
    "Finding Dory",
    "Brave",
    "Tangled",
    "Encanto",
    "Zootopia",
    "Ratatouille",
    "Wall E",
    "Monsters Inc",
    "Monsters University",
    "The Incredibles",
    "Cars 2",
    "Cars 3",
    "The Little Mermaid",
    "Beauty and the Beast",
    "Snow White",
    "Pinocchio",
    "Dumbo",
    "Bambi",
    "Bolt",
    "Big Hero 6",
    "Wreck It Ralph",
    "Ralph Breaks the Internet",
    "Despicable Me",
    "Despicable Me 2",
    "Despicable Me 3",
    "Kung Fu Panda 2",
    "Kung Fu Panda 3",
    "Madagascar",
    "Shrek 2",
    "Shrek 3",
    "The Boss Baby",
    "How to Train Your Dragon",
    "Ice Age",
    "Rio",
    "The Croods",
    "Sing",
    "Sing 2",
    "The Secret Life of Pets",
    "The Lego Movie",
    "Jumanji",
    "The Jungle Book",
    "Mary Poppins",
    "Peter Pan",
    "Tarzan",
    "Hercules",
    "Luca",
    "Soul",
    "Onward",
    "Elemental",
    "Lightyear",
    "Doctor Strange",
    "Captain America",
    "Captain Marvel",
    "Black Widow",
    "Guardians of the Galaxy",
    "The Avengers",
    "Aquaman",
    "Wonder Woman",
    "The Flash",
    "Black Adam",
    "Venom",
    "Thor Ragnarok",
    "Ant Man and the Wasp",
    "The Batman",
    "Mission Impossible",
  ], "Famous"),
  famous_people: createEasyEntries([
    "Amitabh Bachchan",
    "Salman Khan",
    "Aamir Khan",
    "Ranbir Kapoor",
    "Ranveer Singh",
    "Hrithik Roshan",
    "Akshay Kumar",
    "Ajay Devgn",
    "Kareena Kapoor",
    "Alia Bhatt",
    "Katrina Kaif",
    "Anushka Sharma",
    "Kiara Advani",
    "Madhuri Dixit",
    "Kajal Aggarwal",
    "Allu Arjun",
    "Prabhas",
    "Rajinikanth",
    "Vijay",
    "Ram Charan",
    "Jr NTR",
    "Rohit Sharma",
    "MS Dhoni",
    "Hardik Pandya",
    "Jasprit Bumrah",
    "Ravindra Jadeja",
    "KL Rahul",
    "Sunil Chhetri",
    "Neeraj Chopra",
    "PV Sindhu",
    "Saina Nehwal",
    "Mary Kom",
    "Kapil Sharma",
    "A R Rahman",
    "Arijit Singh",
    "Shreya Ghoshal",
    "Justin Bieber",
    "Bruno Mars",
    "Lady Gaga",
    "Katy Perry",
    "Jennifer Lopez",
    "Robert Downey Jr",
    "Chris Hemsworth",
    "Scarlett Johansson",
    "Will Smith",
    "Johnny Depp",
    "Brad Pitt",
    "Angelina Jolie",
    "Dua Lipa",
    "Billie Eilish",
    "Harry Styles",
    "Justin Timberlake",
    "LeBron James",
    "Kobe Bryant",
    "Stephen Curry",
    "David Beckham",
    "Kylian Mbappe",
    "Pele",
    "Diego Maradona",
    "Mark Zuckerberg",
    "Steve Jobs",
    "Sundar Pichai",
    "Satya Nadella",
    "Mukesh Ambani",
    "Ratan Tata",
  ], "Known"),
  brands: createEasyEntries([
    "Reebok",
    "Under Armour",
    "Asics",
    "New Balance",
    "Sketchers",
    "Fila",
    "Vans",
    "Converse",
    "Crocs",
    "Levis",
    "Wrangler",
    "Gap",
    "Uniqlo",
    "Tommy Hilfiger",
    "Calvin Klein",
    "Patanjali",
    "Amul",
    "Parle",
    "Britannia",
    "Nestle",
    "Maggi",
    "Lays",
    "Doritos",
    "KitKat",
    "Ferrero Rocher",
    "Dairy Milk",
    "Red Bull",
    "Monster",
    "Sprite",
    "Fanta",
    "Mountain Dew",
    "Tata",
    "Mahindra",
    "Hyundai",
    "Kia",
    "Ford",
    "Audi",
    "Porsche",
    "Ferrari",
    "Lamborghini",
    "Lenovo",
    "Dell",
    "HP",
    "Asus",
    "Acer",
    "Intel",
    "AMD",
    "Nvidia",
    "JBL",
    "Boat",
    "Noise",
    "OnePlus",
    "Vivo",
    "Oppo",
    "Xiaomi",
    "Realme",
    "Snapchat",
    "Instagram",
    "WhatsApp",
    "Telegram",
    "Discord",
    "Paytm",
    "PhonePe",
    "Swiggy",
    "Zomato",
  ], "Popular"),
  hobbies: createEasyEntries([
    "Walking",
    "Jogging",
    "Listening to Music",
    "Watching Movies",
    "Watching TV",
    "Watching Cricket",
    "Watching Football",
    "Collecting Coins",
    "Collecting Stamps",
    "Scrapbooking",
    "Sewing",
    "Embroidery",
    "Crochet",
    "Woodworking",
    "Paper Craft",
    "Card Making",
    "Model Building",
    "Puzzle Solving",
    "Sudoku",
    "Crossword",
    "Board Games",
    "Card Games",
    "Video Editing",
    "Photo Editing",
    "Animation",
    "Songwriting",
    "Beatboxing",
    "Playing Guitar",
    "Playing Piano",
    "Playing Drums",
    "Playing Violin",
    "Learning Languages",
    "Public Speaking",
    "Acting",
    "Stand Up Comedy",
    "Vlogging",
    "Content Creating",
    "Podcast Listening",
    "Watching Documentaries",
    "Stargazing",
    "People Watching",
    "Pet Care",
    "Dog Walking",
    "Home Decor",
    "Room Designing",
    "Fashion Styling",
    "Makeup Practice",
    "Nail Art",
    "Binge Watching",
    "Tea Tasting",
    "Coffee Brewing",
    "Running Club",
    "Nature Walks",
    "Treasure Hunting",
    "Kite Flying",
    "Balloon Art",
    "Beat Making",
    "DJ Mixing",
    "Learning Magic",
    "Toy Collecting",
    "Watching Cartoons",
    "Listening to Podcasts",
    "Memory Games",
    "Trivia Games",
    "Dance Practice",
  ], "Fun"),
  vehicles: createEasyEntries([
    "Jeep",
    "Sedan",
    "SUV",
    "Hatchback",
    "Convertible",
    "Limousine",
    "Wagon",
    "Auto Rickshaw",
    "School Bus",
    "Double Decker Bus",
    "Bullet Train",
    "Freight Train",
    "Tram",
    "Cable Tram",
    "Rickety Cart",
    "Bullock Cart",
    "Horse Cart",
    "Golf Cart",
    "Tow Truck",
    "Garbage Truck",
    "Cement Mixer",
    "Dump Truck",
    "Crane Truck",
    "Forklift",
    "Excavator",
    "Road Roller",
    "Ambulance Van",
    "Patrol Bike",
    "Speed Boat",
    "Fishing Boat",
    "Row Boat",
    "Jet Boat",
    "Cargo Ship",
    "Sailboat",
    "Raft",
    "Canoe",
    "Kayak",
    "Pedal Boat",
    "Yacht Boat",
    "Fighter Jet",
    "Cargo Plane",
    "Passenger Plane",
    "Glider Plane",
    "Seaplane",
    "Paraglider",
    "Gondola Lift",
    "Snowmobile",
    "Segway",
    "Hoverboard",
    "Electric Scooter",
    "E Bike",
    "Pickup Van",
    "Mini Truck",
    "Camper Van",
    "Caravan",
    "Tricycle",
    "Unicycle",
    "Baby Stroller",
    "Wheelchair",
    "Tram Car",
    "Metro Train",
    "Monorail Train",
    "Helicopter Ambulance",
    "Rescue Boat",
    "Police Van",
  ], "Moving"),
  technology: createEasyEntries([
    "Computer",
    "Desktop",
    "CPU",
    "Hard Disk",
    "SSD",
    "RAM",
    "Graphics Card",
    "Motherboard",
    "Webcam",
    "Earbuds",
    "Smart Speaker",
    "Power Bank",
    "Tripod",
    "Ring Light",
    "Green Screen",
    "Touchscreen",
    "Stylus",
    "Scanner",
    "Photocopier",
    "Projector Screen",
    "Extension Board",
    "Adapter",
    "SIM Card",
    "Memory Card",
    "Pendrive",
    "Data Cable",
    "Remote Control",
    "Game Controller",
    "Smart Bulb",
    "Smart Lock",
    "Smart Camera",
    "Doorbell Camera",
    "Fitness Band",
    "Smart Ring",
    "Microchip",
    "Circuit Board",
    "Sensor",
    "GPS",
    "QR Code",
    "Barcode",
    "Mobile App",
    "Video Call",
    "Live Stream",
    "Podcast Mic",
    "Laptop Stand",
    "Cooling Pad",
    "Docking Station",
    "WiFi Router",
    "Modem",
    "Smart Plug",
    "Robot Vacuum",
    "Digital Clock",
    "Calculator Watch",
    "E Reader",
    "Tablet Pen",
    "Phone Stand",
    "Mini Speaker",
    "Action Camera",
    "Smart Glasses",
    "Drone Camera",
    "Voice Assistant",
    "Password Manager",
    "Search Bar",
    "Online Map",
    "Touch Pad",
  ], "Modern"),
  countries: createEasyEntries([
    "Afghanistan",
    "Albania",
    "Algeria",
    "Austria",
    "Belgium",
    "Bhutan",
    "Bolivia",
    "Chile",
    "Colombia",
    "Croatia",
    "Cuba",
    "Denmark",
    "Ecuador",
    "Ethiopia",
    "Hungary",
    "Iceland",
    "Iran",
    "Iraq",
    "Israel",
    "Jamaica",
    "Jordan",
    "Kazakhstan",
    "Kuwait",
    "Laos",
    "Lebanon",
    "Malaysia",
    "Maldives",
    "Mongolia",
    "Morocco",
    "Myanmar",
    "Oman",
    "Peru",
    "Philippines",
    "Poland",
    "Qatar",
    "Romania",
    "Sri Lanka",
    "Sudan",
    "Syria",
    "Taiwan",
    "Tunisia",
    "Uganda",
    "Ukraine",
    "Uruguay",
    "Vietnam",
    "Yemen",
    "Zimbabwe",
    "Belarus",
    "Bulgaria",
    "Cambodia",
    "Cameroon",
    "Ghana",
    "Lithuania",
    "Luxembourg",
    "Malta",
    "Panama",
    "Paraguay",
    "Serbia",
    "Slovakia",
    "Slovenia",
    "Tanzania",
    "Venezuela",
    "Zambia",
    "Estonia",
    "Latvia",
  ], "World"),
};
