export const categories = {
  food: [
    { word: "Pizza", hint: "Popular" },
    { word: "Burger", hint: "Common" },
    { word: "Pasta", hint: "Comfort" },
    { word: "Sushi", hint: "Trendy" },
    { word: "Sandwich", hint: "Simple" },
    { word: "Ice Cream", hint: "Loved" },
    { word: "Cake", hint: "Celebration" },
    { word: "Chocolate", hint: "Craving" },
    { word: "Fries", hint: "Addictive" },
    { word: "Donut", hint: "Cheerful" },
    { word: "Noodles", hint: "Slurpy" },
    { word: "Rice", hint: "Essential" },
    { word: "Salad", hint: "Fresh" },
    { word: "Soup", hint: "Cozy" },
    { word: "Taco", hint: "Fun" },
  ],
  animals: [
    { word: "Dog", hint: "Friendly" },
    { word: "Cat", hint: "Attitude" },
    { word: "Lion", hint: "Powerful" },
    { word: "Tiger", hint: "Fierce" },
    { word: "Elephant", hint: "Massive" },
    { word: "Monkey", hint: "Mischief" },
    { word: "Horse", hint: "Graceful" },
    { word: "Cow", hint: "Calm" },
    { word: "Bear", hint: "Heavy" },
    { word: "Wolf", hint: "Wild" },
    { word: "Rabbit", hint: "Gentle" },
    { word: "Fox", hint: "Clever" },
    { word: "Deer", hint: "Quiet" },
    { word: "Zebra", hint: "Striking" },
    { word: "Giraffe", hint: "Tall" },
  ],
  movies: [
    { word: "Avatar", hint: "Epic" },
    { word: "Titanic", hint: "Legendary" },
    { word: "Inception", hint: "Mindbending" },
    { word: "Batman", hint: "Dark" },
    { word: "Joker", hint: "Chaotic" },
    { word: "Frozen", hint: "Beloved" },
    { word: "Avengers", hint: "Massive" },
    { word: "Spider-Man", hint: "Iconic" },
    { word: "Superman", hint: "Classic" },
    { word: "Iron Man", hint: "Cool" },
    { word: "Hulk", hint: "Smash" },
    { word: "Minions", hint: "Silly" },
    { word: "Cars", hint: "Speedy" },
    { word: "Aladdin", hint: "Magical" },
    { word: "Cinderella", hint: "Dreamy" },
  ],
  places: [
    { word: "Beach", hint: "Relaxed" },
    { word: "School", hint: "Routine" },
    { word: "Airport", hint: "Busy" },
    { word: "Hospital", hint: "Serious" },
    { word: "Mall", hint: "Crowded" },
    { word: "Restaurant", hint: "Social" },
    { word: "Park", hint: "Open" },
    { word: "Cinema", hint: "Immersive" },
    { word: "Hotel", hint: "Temporary" },
    { word: "Library", hint: "Quiet" },
    { word: "Gym", hint: "Intense" },
    { word: "Office", hint: "Formal" },
    { word: "Temple", hint: "Sacred" },
    { word: "Market", hint: "Lively" },
    { word: "Zoo", hint: "Curious" },
  ],
  jobs: [
    { word: "Doctor", hint: "Trusted" },
    { word: "Engineer", hint: "Precise" },
    { word: "Teacher", hint: "Guiding" },
    { word: "Police", hint: "Strict" },
    { word: "Chef", hint: "Creative" },
    { word: "Farmer", hint: "Grounded" },
    { word: "Driver", hint: "Steady" },
    { word: "Pilot", hint: "Elite" },
    { word: "Actor", hint: "Famous" },
    { word: "Singer", hint: "Expressive" },
    { word: "Lawyer", hint: "Sharp" },
    { word: "Designer", hint: "Stylish" },
    { word: "Developer", hint: "Logical" },
    { word: "Nurse", hint: "Caring" },
    { word: "Scientist", hint: "Curious" },
  ],
  objects: [
    { word: "Phone", hint: "Essential" },
    { word: "Laptop", hint: "Modern" },
    { word: "Bottle", hint: "Basic" },
    { word: "Chair", hint: "Ordinary" },
    { word: "Table", hint: "Stable" },
    { word: "Book", hint: "Thoughtful" },
    { word: "Pen", hint: "Simple" },
    { word: "Watch", hint: "Classic" },
    { word: "Bag", hint: "Useful" },
    { word: "Camera", hint: "Capture" },
    { word: "Keyboard", hint: "Clicky" },
    { word: "Mouse", hint: "Handy" },
    { word: "Fan", hint: "Cooling" },
    { word: "TV", hint: "Casual" },
    { word: "Speaker", hint: "Loud" },
  ],
  sports: [
    { word: "Cricket", hint: "Famous" },
    { word: "Football", hint: "Global" },
    { word: "Basketball", hint: "Fast" },
    { word: "Tennis", hint: "Elite" },
    { word: "Hockey", hint: "Sharp" },
    { word: "Badminton", hint: "Quick" },
    { word: "Golf", hint: "Calm" },
    { word: "Baseball", hint: "Classic" },
    { word: "Rugby", hint: "Rough" },
    { word: "Swimming", hint: "Olympic" },
    { word: "Boxing", hint: "Intense" },
    { word: "Cycling", hint: "Endurance" },
    { word: "Running", hint: "Pure" },
    { word: "Skating", hint: "Smooth" },
    { word: "Wrestling", hint: "Dramatic" },
  ],
  hobbies: [
    { word: "Reading", hint: "Quiet" },
    { word: "Gaming", hint: "Addictive" },
    { word: "Cooking", hint: "Comfort" },
    { word: "Painting", hint: "Expressive" },
    { word: "Dancing", hint: "Energetic" },
    { word: "Singing", hint: "Emotional" },
    { word: "Traveling", hint: "Free" },
    { word: "Photography", hint: "Aesthetic" },
    { word: "Writing", hint: "Reflective" },
    { word: "Fishing", hint: "Patient" },
    { word: "Gardening", hint: "Peaceful" },
    { word: "Drawing", hint: "Creative" },
    { word: "Coding", hint: "Focused" },
    { word: "Yoga", hint: "Balanced" },
    { word: "Shopping", hint: "Impulsive" },
  ],
};

export function getRandomWord(category) {
  const words = categories[category] ?? categories.food;
  return words[Math.floor(Math.random() * words.length)];
}
