import { getRandomPair } from "./doubleWordPairs";

export const categories = {
  food: [
    { word: "Pizza", hint: "Popular" },
    { word: "Burger", hint: "Common" },
    { word: "Pasta", hint: "Comfort" },
    { word: "Sushi", hint: "Trendy" },
    { word: "Sandwich", hint: "Simple" },
    { word: "Ice Cream", hint: "Loved" },
    { word: "Cake", hint: "Celebration" },
    { word: "Chocolate", hint: "Craving" },
    { word: "Fries", hint: "Addictive" },
    { word: "Donut", hint: "Cheerful" },
    { word: "Noodles", hint: "Slurpy" },
    { word: "Rice", hint: "Essential" },
    { word: "Salad", hint: "Fresh" },
    { word: "Soup", hint: "Cozy" },
    { word: "Taco", hint: "Fun" },
    { word: "Pancake", hint: "Warm" },
    { word: "Waffle", hint: "Sweet" },
    { word: "Biryani", hint: "Rich" },
    { word: "Dumpling", hint: "Comfort" },
    { word: "Steak", hint: "Bold" },
    { word: "Sausage", hint: "Hearty" },
    { word: "Apple", hint: "Classic" },
    { word: "Banana", hint: "Playful" },
    { word: "Orange", hint: "Bright" },
    { word: "Mango", hint: "Tropical" },
    { word: "Grapes", hint: "Juicy" },
    { word: "Watermelon", hint: "Summer" },
    { word: "Popcorn", hint: "Movie" },
    { word: "Cookie", hint: "Treat" },
    { word: "Brownie", hint: "Rich" },
    { word: "Cheese", hint: "Savory" },
    { word: "Omelet", hint: "Morning" },
    { word: "Curry", hint: "Intense" },
    { word: "Hotdog", hint: "Street" },
    { word: "Muffin", hint: "Cute" },
    { word: "Croissant", hint: "Fancy" },
    { word: "Milkshake", hint: "Creamy" },
    { word: "Lasagna", hint: "Layered" },
    { word: "Cupcake", hint: "Joyful" },
  ],
  animals: [
    { word: "Dog", hint: "Friendly" },
    { word: "Cat", hint: "Attitude" },
    { word: "Lion", hint: "Powerful" },
    { word: "Tiger", hint: "Fierce" },
    { word: "Elephant", hint: "Massive" },
    { word: "Monkey", hint: "Mischief" },
    { word: "Horse", hint: "Graceful" },
    { word: "Cow", hint: "Calm" },
    { word: "Bear", hint: "Heavy" },
    { word: "Wolf", hint: "Wild" },
    { word: "Rabbit", hint: "Gentle" },
    { word: "Fox", hint: "Clever" },
    { word: "Deer", hint: "Quiet" },
    { word: "Zebra", hint: "Striking" },
    { word: "Giraffe", hint: "Tall" },
    { word: "Panda", hint: "Adored" },
    { word: "Koala", hint: "Sleepy" },
    { word: "Kangaroo", hint: "Bouncy" },
    { word: "Penguin", hint: "Charming" },
    { word: "Dolphin", hint: "Smart" },
    { word: "Whale", hint: "Giant" },
    { word: "Shark", hint: "Sharp" },
    { word: "Octopus", hint: "Weird" },
    { word: "Peacock", hint: "Proud" },
    { word: "Parrot", hint: "Noisy" },
    { word: "Camel", hint: "Tough" },
    { word: "Goat", hint: "Stubborn" },
    { word: "Sheep", hint: "Soft" },
    { word: "Pig", hint: "Playful" },
    { word: "Chicken", hint: "Busy" },
    { word: "Duck", hint: "Goofy" },
    { word: "Frog", hint: "Jumping" },
    { word: "Snake", hint: "Slippery" },
    { word: "Eagle", hint: "Majestic" },
    { word: "Owl", hint: "Wise" },
    { word: "Crocodile", hint: "Dangerous" },
    { word: "Leopard", hint: "Swift" },
    { word: "Otter", hint: "Cute" },
    { word: "Hippopotamus", hint: "Massive" },
  ],
  sports: [
    { word: "Cricket", hint: "Famous" },
    { word: "Football", hint: "Global" },
    { word: "Basketball", hint: "Fast" },
    { word: "Tennis", hint: "Elite" },
    { word: "Hockey", hint: "Sharp" },
    { word: "Badminton", hint: "Quick" },
    { word: "Golf", hint: "Calm" },
    { word: "Baseball", hint: "Classic" },
    { word: "Rugby", hint: "Rough" },
    { word: "Swimming", hint: "Olympic" },
    { word: "Boxing", hint: "Intense" },
    { word: "Cycling", hint: "Endurance" },
    { word: "Running", hint: "Pure" },
    { word: "Skating", hint: "Smooth" },
    { word: "Wrestling", hint: "Dramatic" },
    { word: "Volleyball", hint: "Energetic" },
    { word: "Table Tennis", hint: "Rapid" },
    { word: "Karate", hint: "Disciplined" },
    { word: "Judo", hint: "Focused" },
    { word: "Gymnastics", hint: "Graceful" },
    { word: "Surfing", hint: "Cool" },
    { word: "Skiing", hint: "Icy" },
    { word: "Snowboarding", hint: "Stylish" },
    { word: "Archery", hint: "Precise" },
    { word: "Fencing", hint: "Sharp" },
    { word: "Rowing", hint: "Steady" },
    { word: "Diving", hint: "Fearless" },
    { word: "Snooker", hint: "Quiet" },
    { word: "Pool", hint: "Smooth" },
    { word: "Bowling", hint: "Casual" },
    { word: "Skateboarding", hint: "Rebellious" },
    { word: "Formula One", hint: "Speed" },
    { word: "MotoGP", hint: "Risky" },
    { word: "Handball", hint: "Underrated" },
    { word: "Lacrosse", hint: "Niche" },
    { word: "Water Polo", hint: "Tough" },
    { word: "Softball", hint: "Friendly" },
    { word: "Marathon", hint: "Grueling" },
    { word: "Chess", hint: "Mental" },
  ],
  jobs: [
    { word: "Doctor", hint: "Trusted" },
    { word: "Engineer", hint: "Precise" },
    { word: "Teacher", hint: "Guiding" },
    { word: "Police", hint: "Strict" },
    { word: "Chef", hint: "Creative" },
    { word: "Farmer", hint: "Grounded" },
    { word: "Driver", hint: "Steady" },
    { word: "Pilot", hint: "Elite" },
    { word: "Actor", hint: "Famous" },
    { word: "Singer", hint: "Expressive" },
    { word: "Lawyer", hint: "Sharp" },
    { word: "Designer", hint: "Stylish" },
    { word: "Developer", hint: "Logical" },
    { word: "Nurse", hint: "Caring" },
    { word: "Scientist", hint: "Curious" },
    { word: "Firefighter", hint: "Brave" },
    { word: "Dentist", hint: "Nervous" },
    { word: "Writer", hint: "Thoughtful" },
    { word: "Journalist", hint: "Alert" },
    { word: "Photographer", hint: "Artistic" },
    { word: "Dancer", hint: "Graceful" },
    { word: "Athlete", hint: "Driven" },
    { word: "Architect", hint: "Visionary" },
    { word: "Mechanic", hint: "Practical" },
    { word: "Electrician", hint: "Skilled" },
    { word: "Plumber", hint: "Handy" },
    { word: "Cashier", hint: "Routine" },
    { word: "Barber", hint: "Social" },
    { word: "Tailor", hint: "Neat" },
    { word: "Soldier", hint: "Disciplined" },
    { word: "Judge", hint: "Serious" },
    { word: "Therapist", hint: "Gentle" },
    { word: "Professor", hint: "Wise" },
    { word: "Librarian", hint: "Quiet" },
    { word: "Waiter", hint: "Busy" },
    { word: "Baker", hint: "Warm" },
    { word: "Model", hint: "Glamorous" },
    { word: "Director", hint: "Commanding" },
    { word: "Astronaut", hint: "Rare" },
  ],
  objects: [
    { word: "Phone", hint: "Essential" },
    { word: "Laptop", hint: "Modern" },
    { word: "Bottle", hint: "Basic" },
    { word: "Chair", hint: "Ordinary" },
    { word: "Table", hint: "Stable" },
    { word: "Book", hint: "Thoughtful" },
    { word: "Pen", hint: "Simple" },
    { word: "Watch", hint: "Classic" },
    { word: "Bag", hint: "Useful" },
    { word: "Camera", hint: "Capture" },
    { word: "Keyboard", hint: "Clicky" },
    { word: "Mouse", hint: "Handy" },
    { word: "Fan", hint: "Cooling" },
    { word: "TV", hint: "Casual" },
    { word: "Speaker", hint: "Loud" },
    { word: "Spoon", hint: "Everyday" },
    { word: "Fork", hint: "Simple" },
    { word: "Knife", hint: "Sharp" },
    { word: "Plate", hint: "Plain" },
    { word: "Pillow", hint: "Soft" },
    { word: "Blanket", hint: "Cozy" },
    { word: "Mirror", hint: "Reflective" },
    { word: "Clock", hint: "Ticking" },
    { word: "Lamp", hint: "Warm" },
    { word: "Sofa", hint: "Comfort" },
    { word: "Toothbrush", hint: "Routine" },
    { word: "Comb", hint: "Neat" },
    { word: "Wallet", hint: "Personal" },
    { word: "Helmet", hint: "Protective" },
    { word: "Umbrella", hint: "Prepared" },
    { word: "Scissors", hint: "Snappy" },
    { word: "Backpack", hint: "Practical" },
    { word: "Glasses", hint: "Smart" },
    { word: "Headphones", hint: "Immersive" },
    { word: "Remote", hint: "Lazy" },
    { word: "Microwave", hint: "Quick" },
    { word: "Refrigerator", hint: "Cold" },
    { word: "Toaster", hint: "Morning" },
    { word: "Candle", hint: "Calm" },
  ],
  places: [
    { word: "Beach", hint: "Relaxed" },
    { word: "School", hint: "Routine" },
    { word: "Airport", hint: "Busy" },
    { word: "Hospital", hint: "Serious" },
    { word: "Mall", hint: "Crowded" },
    { word: "Restaurant", hint: "Social" },
    { word: "Park", hint: "Open" },
    { word: "Cinema", hint: "Immersive" },
    { word: "Hotel", hint: "Temporary" },
    { word: "Library", hint: "Quiet" },
    { word: "Gym", hint: "Intense" },
    { word: "Office", hint: "Formal" },
    { word: "Temple", hint: "Sacred" },
    { word: "Market", hint: "Lively" },
    { word: "Zoo", hint: "Curious" },
    { word: "Museum", hint: "Historic" },
    { word: "Stadium", hint: "Electric" },
    { word: "Cafe", hint: "Casual" },
    { word: "Bakery", hint: "Warm" },
    { word: "Bridge", hint: "Iconic" },
    { word: "Castle", hint: "Grand" },
    { word: "Farm", hint: "Peaceful" },
    { word: "Island", hint: "Remote" },
    { word: "Desert", hint: "Harsh" },
    { word: "Forest", hint: "Quiet" },
    { word: "Mountain", hint: "Majestic" },
    { word: "River", hint: "Flowing" },
    { word: "Lake", hint: "Still" },
    { word: "Village", hint: "Humble" },
    { word: "Subway", hint: "Rushed" },
    { word: "Station", hint: "Transit" },
    { word: "Bank", hint: "Serious" },
    { word: "Aquarium", hint: "Mesmerizing" },
    { word: "Playground", hint: "Joyful" },
    { word: "Factory", hint: "Noisy" },
    { word: "Harbor", hint: "Busy" },
    { word: "Tower", hint: "Tall" },
    { word: "Theater", hint: "Dramatic" },
    { word: "University", hint: "Ambitious" },
  ],
  movies: [
    { word: "Avatar", hint: "Epic" },
    { word: "Titanic", hint: "Legendary" },
    { word: "Inception", hint: "Mindbending" },
    { word: "Batman", hint: "Dark" },
    { word: "Joker", hint: "Chaotic" },
    { word: "Frozen", hint: "Beloved" },
    { word: "Avengers", hint: "Massive" },
    { word: "Spider-Man", hint: "Iconic" },
    { word: "Superman", hint: "Classic" },
    { word: "Iron Man", hint: "Cool" },
    { word: "Hulk", hint: "Smash" },
    { word: "Minions", hint: "Silly" },
    { word: "Cars", hint: "Speedy" },
    { word: "Aladdin", hint: "Magical" },
    { word: "Cinderella", hint: "Dreamy" },
    { word: "Barbie", hint: "Bright" },
    { word: "Shrek", hint: "Funny" },
    { word: "Moana", hint: "Adventure" },
    { word: "Coco", hint: "Heartfelt" },
    { word: "Jaws", hint: "Fearful" },
    { word: "Rocky", hint: "Motivating" },
    { word: "Gladiator", hint: "Intense" },
    { word: "Interstellar", hint: "Cosmic" },
    { word: "Mulan", hint: "Brave" },
    { word: "Up", hint: "Emotional" },
    { word: "Finding Nemo", hint: "Cute" },
    { word: "Toy Story", hint: "Nostalgic" },
    { word: "The Matrix", hint: "Stylish" },
    { word: "Harry Potter", hint: "Magical" },
    { word: "Star Wars", hint: "Legendary" },
    { word: "Jurassic Park", hint: "Wild" },
    { word: "Home Alone", hint: "Classic" },
    { word: "Deadpool", hint: "Sarcastic" },
    { word: "Black Panther", hint: "Powerful" },
    { word: "Thor", hint: "Mighty" },
    { word: "Ant-Man", hint: "Quirky" },
    { word: "Inside Out", hint: "Emotional" },
    { word: "The Lion King", hint: "Majestic" },
    { word: "Kung Fu Panda", hint: "Playful" },
  ],
  famous_people: [
    { word: "Messi", hint: "Legendary" },
    { word: "Ronaldo", hint: "Global" },
    { word: "Taylor Swift", hint: "Massive" },
    { word: "Beyonce", hint: "Powerful" },
    { word: "Shah Rukh Khan", hint: "Iconic" },
    { word: "Tom Cruise", hint: "Fearless" },
    { word: "Leonardo DiCaprio", hint: "Famous" },
    { word: "Michael Jackson", hint: "Legendary" },
    { word: "Elon Musk", hint: "Polarizing" },
    { word: "Bill Gates", hint: "Influential" },
    { word: "Oprah", hint: "Powerful" },
    { word: "Virat Kohli", hint: "Intense" },
    { word: "Sachin Tendulkar", hint: "Revered" },
    { word: "Neymar", hint: "Flashy" },
    { word: "Zlatan", hint: "Bold" },
    { word: "Selena Gomez", hint: "Beloved" },
    { word: "Ariana Grande", hint: "Popular" },
    { word: "Drake", hint: "Mainstream" },
    { word: "Rihanna", hint: "Stylish" },
    { word: "Chris Evans", hint: "Charming" },
    { word: "Dwayne Johnson", hint: "Massive" },
    { word: "Keanu Reeves", hint: "Cool" },
    { word: "Zendaya", hint: "Trendy" },
    { word: "Emma Watson", hint: "Graceful" },
    { word: "Adele", hint: "Soulful" },
    { word: "Ed Sheeran", hint: "Warm" },
    { word: "Usain Bolt", hint: "Fast" },
    { word: "Michael Jordan", hint: "Elite" },
    { word: "Serena Williams", hint: "Dominant" },
    { word: "Roger Federer", hint: "Elegant" },
    { word: "Novak Djokovic", hint: "Relentless" },
    { word: "Priyanka Chopra", hint: "Global" },
    { word: "Deepika Padukone", hint: "Elegant" },
    { word: "Cristiano Ronaldo", hint: "Driven" },
    { word: "Albert Einstein", hint: "Brilliant" },
    { word: "Mahatma Gandhi", hint: "Historic" },
    { word: "Nelson Mandela", hint: "Inspiring" },
    { word: "Marilyn Monroe", hint: "Timeless" },
    { word: "Elvis Presley", hint: "Classic" },
  ],
  brands: [
    { word: "Nike", hint: "Athletic" },
    { word: "Adidas", hint: "Sporty" },
    { word: "Apple", hint: "Premium" },
    { word: "Samsung", hint: "Global" },
    { word: "Google", hint: "Everywhere" },
    { word: "Amazon", hint: "Massive" },
    { word: "Microsoft", hint: "Essential" },
    { word: "Coca-Cola", hint: "Classic" },
    { word: "Pepsi", hint: "Familiar" },
    { word: "McDonalds", hint: "Famous" },
    { word: "KFC", hint: "Crispy" },
    { word: "Starbucks", hint: "Trendy" },
    { word: "Toyota", hint: "Reliable" },
    { word: "BMW", hint: "Luxury" },
    { word: "Mercedes", hint: "Elegant" },
    { word: "Tesla", hint: "Future" },
    { word: "Honda", hint: "Practical" },
    { word: "Sony", hint: "Trusted" },
    { word: "LG", hint: "Everyday" },
    { word: "Puma", hint: "Active" },
    { word: "Zara", hint: "Stylish" },
    { word: "H&M", hint: "Mainstream" },
    { word: "IKEA", hint: "Minimal" },
    { word: "Netflix", hint: "Addictive" },
    { word: "Disney", hint: "Magical" },
    { word: "YouTube", hint: "Viral" },
    { word: "Spotify", hint: "Daily" },
    { word: "Uber", hint: "Convenient" },
    { word: "Airbnb", hint: "Flexible" },
    { word: "Rolex", hint: "Prestige" },
    { word: "Gucci", hint: "Flashy" },
    { word: "Prada", hint: "Exclusive" },
    { word: "Lego", hint: "Creative" },
    { word: "Canon", hint: "Sharp" },
    { word: "Nikon", hint: "Classic" },
    { word: "Shell", hint: "Familiar" },
    { word: "Subway", hint: "Quick" },
    { word: "Dominos", hint: "Popular" },
    { word: "PlayStation", hint: "Fun" },
  ],
  hobbies: [
    { word: "Reading", hint: "Quiet" },
    { word: "Gaming", hint: "Addictive" },
    { word: "Cooking", hint: "Comfort" },
    { word: "Painting", hint: "Expressive" },
    { word: "Dancing", hint: "Energetic" },
    { word: "Singing", hint: "Emotional" },
    { word: "Traveling", hint: "Free" },
    { word: "Photography", hint: "Aesthetic" },
    { word: "Writing", hint: "Reflective" },
    { word: "Fishing", hint: "Patient" },
    { word: "Gardening", hint: "Peaceful" },
    { word: "Drawing", hint: "Creative" },
    { word: "Coding", hint: "Focused" },
    { word: "Yoga", hint: "Balanced" },
    { word: "Shopping", hint: "Impulsive" },
    { word: "Running", hint: "Freeing" },
    { word: "Cycling", hint: "Driven" },
    { word: "Swimming", hint: "Calming" },
    { word: "Hiking", hint: "Adventurous" },
    { word: "Camping", hint: "Rustic" },
    { word: "Knitting", hint: "Gentle" },
    { word: "Chess", hint: "Strategic" },
    { word: "Puzzles", hint: "Mental" },
    { word: "Collecting", hint: "Obsessive" },
    { word: "Blogging", hint: "Public" },
    { word: "Journaling", hint: "Private" },
    { word: "Meditation", hint: "Still" },
    { word: "Baking", hint: "Warm" },
    { word: "Skateboarding", hint: "Cool" },
    { word: "Surfing", hint: "Chill" },
    { word: "Crafting", hint: "Handmade" },
    { word: "Calligraphy", hint: "Elegant" },
    { word: "Origami", hint: "Delicate" },
    { word: "Podcasting", hint: "Talkative" },
    { word: "Streaming", hint: "Live" },
    { word: "Watching Anime", hint: "Passionate" },
    { word: "Birdwatching", hint: "Patient" },
    { word: "DIY", hint: "Handy" },
    { word: "Pottery", hint: "Earthy" },
  ],
  vehicles: [
    { word: "Car", hint: "Everyday" },
    { word: "Bus", hint: "Crowded" },
    { word: "Train", hint: "Steady" },
    { word: "Bicycle", hint: "Simple" },
    { word: "Motorcycle", hint: "Bold" },
    { word: "Scooter", hint: "Casual" },
    { word: "Truck", hint: "Heavy" },
    { word: "Van", hint: "Practical" },
    { word: "Taxi", hint: "Urban" },
    { word: "Ambulance", hint: "Urgent" },
    { word: "Police Car", hint: "Serious" },
    { word: "Fire Truck", hint: "Loud" },
    { word: "Helicopter", hint: "Dramatic" },
    { word: "Airplane", hint: "Global" },
    { word: "Jet", hint: "Fast" },
    { word: "Boat", hint: "Calm" },
    { word: "Ship", hint: "Massive" },
    { word: "Yacht", hint: "Luxury" },
    { word: "Submarine", hint: "Secretive" },
    { word: "Tractor", hint: "Rural" },
    { word: "Bulldozer", hint: "Powerful" },
    { word: "Race Car", hint: "Speed" },
    { word: "Formula One", hint: "Elite" },
    { word: "Skateboard", hint: "Rebellious" },
    { word: "Rollerblades", hint: "Playful" },
    { word: "Cable Car", hint: "Scenic" },
    { word: "Ferry", hint: "Slow" },
    { word: "Rocket", hint: "Extreme" },
    { word: "Spaceship", hint: "Futuristic" },
    { word: "Hot Air Balloon", hint: "Dreamy" },
    { word: "Glider", hint: "Silent" },
    { word: "Pickup Truck", hint: "Rugged" },
    { word: "Minivan", hint: "Family" },
    { word: "Tuk Tuk", hint: "Local" },
    { word: "Rickshaw", hint: "Classic" },
    { word: "Metro", hint: "Rushed" },
    { word: "Monorail", hint: "Modern" },
    { word: "ATV", hint: "Wild" },
    { word: "Cruise Ship", hint: "Lavish" },
  ],
  technology: [
    { word: "Internet", hint: "Essential" },
    { word: "Wi-Fi", hint: "Invisible" },
    { word: "App", hint: "Daily" },
    { word: "Robot", hint: "Futuristic" },
    { word: "Drone", hint: "Cool" },
    { word: "Tablet", hint: "Portable" },
    { word: "Smartwatch", hint: "Trendy" },
    { word: "VR Headset", hint: "Immersive" },
    { word: "Headphones", hint: "Private" },
    { word: "Charger", hint: "Needed" },
    { word: "Printer", hint: "Office" },
    { word: "Router", hint: "Hidden" },
    { word: "Server", hint: "Powerful" },
    { word: "Cloud", hint: "Everywhere" },
    { word: "AI", hint: "Buzzing" },
    { word: "Code", hint: "Logical" },
    { word: "Password", hint: "Secret" },
    { word: "Camera", hint: "Sharp" },
    { word: "Microphone", hint: "Clear" },
    { word: "Monitor", hint: "Bright" },
    { word: "Projector", hint: "Big" },
    { word: "Bluetooth", hint: "Wireless" },
    { word: "USB", hint: "Handy" },
    { word: "Battery", hint: "Vital" },
    { word: "Speaker", hint: "Loud" },
    { word: "Console", hint: "Fun" },
    { word: "PlayStation", hint: "Popular" },
    { word: "Xbox", hint: "Competitive" },
    { word: "Laptop", hint: "Work" },
    { word: "Smartphone", hint: "Constant" },
    { word: "Search Engine", hint: "Instant" },
    { word: "Email", hint: "Formal" },
    { word: "Website", hint: "Public" },
    { word: "Keyboard", hint: "Clicky" },
    { word: "Mouse", hint: "Precise" },
    { word: "Flash Drive", hint: "Tiny" },
    { word: "3D Printer", hint: "Inventive" },
    { word: "Satellite", hint: "Distant" },
    { word: "Smart TV", hint: "Connected" },
  ],
  countries: [
    { word: "India", hint: "Vibrant" },
    { word: "USA", hint: "Famous" },
    { word: "China", hint: "Massive" },
    { word: "Japan", hint: "Precise" },
    { word: "Brazil", hint: "Energetic" },
    { word: "France", hint: "Stylish" },
    { word: "Italy", hint: "Classic" },
    { word: "Spain", hint: "Passionate" },
    { word: "Germany", hint: "Efficient" },
    { word: "Canada", hint: "Polite" },
    { word: "Australia", hint: "Relaxed" },
    { word: "Mexico", hint: "Colorful" },
    { word: "Russia", hint: "Cold" },
    { word: "Egypt", hint: "Historic" },
    { word: "South Africa", hint: "Diverse" },
    { word: "Argentina", hint: "Proud" },
    { word: "Portugal", hint: "Coastal" },
    { word: "England", hint: "Classic" },
    { word: "Ireland", hint: "Green" },
    { word: "Scotland", hint: "Bold" },
    { word: "Norway", hint: "Calm" },
    { word: "Sweden", hint: "Minimal" },
    { word: "Finland", hint: "Quiet" },
    { word: "Netherlands", hint: "Chill" },
    { word: "Switzerland", hint: "Neat" },
    { word: "Greece", hint: "Mythic" },
    { word: "Turkey", hint: "Layered" },
    { word: "Saudi Arabia", hint: "Rich" },
    { word: "UAE", hint: "Luxury" },
    { word: "Thailand", hint: "Friendly" },
    { word: "Singapore", hint: "Modern" },
    { word: "Indonesia", hint: "Tropical" },
    { word: "South Korea", hint: "Trendy" },
    { word: "New Zealand", hint: "Fresh" },
    { word: "Kenya", hint: "Wild" },
    { word: "Nigeria", hint: "Lively" },
    { word: "Pakistan", hint: "Passionate" },
    { word: "Bangladesh", hint: "Busy" },
    { word: "Nepal", hint: "Majestic" },
  ],
};

export const chaosWordPairs = {
  food: [
    ["Pizza", "Burger"],
    ["Pasta", "Noodles"],
    ["Cake", "Cupcake"],
    ["Fries", "Chips"],
    ["Taco", "Burrito"],
    ["Waffle", "Pancake"],
    ["Cookie", "Brownie"],
    ["Hotdog", "Sausage"],
  ],
  animals: [
    ["Lion", "Tiger"],
    ["Dog", "Wolf"],
    ["Rabbit", "Hare"],
    ["Crocodile", "Alligator"],
    ["Dolphin", "Whale"],
    ["Goat", "Sheep"],
    ["Eagle", "Hawk"],
    ["Frog", "Toad"],
  ],
  sports: [
    ["Football", "Rugby"],
    ["Tennis", "Badminton"],
    ["Pool", "Snooker"],
    ["Running", "Marathon"],
    ["Skating", "Skateboarding"],
    ["Formula One", "MotoGP"],
    ["Baseball", "Softball"],
    ["Judo", "Karate"],
  ],
  jobs: [
    ["Doctor", "Nurse"],
    ["Teacher", "Professor"],
    ["Designer", "Architect"],
    ["Police", "Soldier"],
    ["Writer", "Journalist"],
    ["Chef", "Baker"],
    ["Actor", "Director"],
    ["Photographer", "Model"],
  ],
  objects: [
    ["Phone", "Laptop"],
    ["Chair", "Sofa"],
    ["Pen", "Pencil"],
    ["Bottle", "Glass"],
    ["Fork", "Spoon"],
    ["Lamp", "Candle"],
    ["Backpack", "Bag"],
    ["Speaker", "Headphones"],
  ],
  places: [
    ["Beach", "Island"],
    ["School", "University"],
    ["Cafe", "Restaurant"],
    ["Library", "Museum"],
    ["Airport", "Station"],
    ["Market", "Mall"],
    ["Farm", "Village"],
    ["Cinema", "Theater"],
  ],
  movies: [
    ["Batman", "Joker"],
    ["Avatar", "Titanic"],
    ["Frozen", "Moana"],
    ["Avengers", "Justice League"],
    ["Spider-Man", "Superman"],
    ["Hulk", "Iron Man"],
    ["Minions", "Toy Story"],
    ["Inception", "Interstellar"],
  ],
  countries: [
    ["India", "Pakistan"],
    ["Japan", "South Korea"],
    ["Canada", "USA"],
    ["Spain", "Portugal"],
    ["Australia", "New Zealand"],
    ["Germany", "Switzerland"],
    ["Norway", "Sweden"],
    ["Thailand", "Indonesia"],
  ],
};

export function getRandomWord(category) {
  const words = categories[category] ?? categories.food;
  return words[Math.floor(Math.random() * words.length)];
}

export function getRandomChaosPair(category) {
  const pairs = chaosWordPairs[category] ?? chaosWordPairs.food;
  const [word, altWord] = pairs[Math.floor(Math.random() * pairs.length)];

  return {
    word,
    altWord,
  };
}

export function getRandomDoubleWordPair(category) {
  return getRandomPair(category);
}
